### PR TITLE
Feature/swepub 2 1033 1032 update data preview

### PR DESCRIPTION
**Pull request by didair**
Updates on the search preview table

### CODE REVIEW

**Comment by andersju** [comment]
It seems like the post count is now wrong (or rather, a bit confusing), as it only refers to one of the previewed organizations. To make a quick example:

```
export SWEPUB_SKIP_REMOTE=1 # just to make harvesting faster
python3 -m pipeline.harvest -f ths uniarts 
python3 -m service.swepub
```

Now, if I go to http://127.0.0.1:5000/bibliometrics and select each of those two, choose 2023 and 2023 and click "Visa", it says "5 poster" (http://127.0.0.1:5000/bibliometrics?org=ths&org=uniarts&from=2023&to=2023).

But that's just the 5 from Enskilda Högskolan Stockholm (ths). The total (as of today) should be 7. Compare with https://bibliometri.swepub.kb.se/bibliometrics?org=uniarts&org=ths&from=2023&to=2023

Seems like we do need to make two separate requests for the new-style preview to work (one to get the total, one just for the preview of one of the organizations) :thinking:

**Comment by didair** [comment]
Yes you are correct, I missed this.. I will make a separate call to fetch the count with limit = 1 so we dont fetch unnecessary data. (Tried setting limit = 0 but it returned all documents)

**Comment by andersju** [comment]
Also, a "Visa föregående" next to "Visa nästa" would be nice, but that's not for me to decide so feel free to ignore :)

**Comment by didair** [comment]
> 

I agree

Added the API call in my latest commit + enabled eslint again in ExportData.vue (ooops)

**Review by andersju — APPROVED** [review]
:+1:

**Pull request merged**
